### add a song
POST http://localhost:5000/api/song
Content-Type: multipart/form-data

{
    "name": "New York Nagaram",
}


###
GET http://localhost:5000/api/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjZjOGIxMzIyNWJiYWRmMDU1OGEzOCIsImlhdCI6MTcxMzgxODM4MywiZXhwIjoxNzQ1Mzc1OTgzfQ.X2i0cgtDxc-huRklDaRksisWsSj5IJl0moyMOLbphts



###
GET http://localhost:5000/api/songs/66254f5805ddeab94eaa3a9a/play
Range: 20



### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "admin@thenisai.com",
    "password": "admin"
}


### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin@thenisai.com",
    "password": "admin"
}

### Create playlist
POST http://localhost:5000/api/playlists/create?name=Test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjZjOGIxMzIyNWJiYWRmMDU1OGEzOCIsImlhdCI6MTcxMzgxODM4MywiZXhwIjoxNzQ1Mzc1OTgzfQ.X2i0cgtDxc-huRklDaRksisWsSj5IJl0moyMOLbphts

### Get all playlist
GET http://localhost:5000/api/playlists/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjZjOGIxMzIyNWJiYWRmMDU1OGEzOCIsImlhdCI6MTcxMzgxODM4MywiZXhwIjoxNzQ1Mzc1OTgzfQ.X2i0cgtDxc-huRklDaRksisWsSj5IJl0moyMOLbphts

### Add song to a playlist
PATCH http://localhost:5000/api/playlists/662740198a35fcacf2c9ae71/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjZjOGIxMzIyNWJiYWRmMDU1OGEzOCIsImlhdCI6MTcxMzgxODM4MywiZXhwIjoxNzQ1Mzc1OTgzfQ.X2i0cgtDxc-huRklDaRksisWsSj5IJl0moyMOLbphts
Content-Type: application/json

{
    "songId": "66269a96fa183be20c663a1d"
}