### add a song
POST http://localhost:5000/api/song
Content-Type: multipart/form-data

{
    "name": "New York Nagaram",
}


###
GET http://localhost:5000/api/songs
Authorization: Bearer 



###
GET http://localhost:5000/api/songs/66254f5805ddeab94eaa3a9a/play
Range: 20



### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "admin@thenisai.com",
    "password": "admin"
}


### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin@thenisai.com",
    "password": "admin"
}

### Create playlist
POST http://localhost:5000/api/playlists/create?name=Test
Authorization: Bearer 
### Get all playlist
GET http://localhost:5000/api/playlists/all
Authorization: Bearer 

### Add song to a playlist
PATCH http://localhost:5000/api/playlists/662740198a35fcacf2c9ae71/add
Authorization: Bearer 
Content-Type: application/json

{
    "songId": "6628b27c3b1ab928b340356e"
}

###
GET http://localhost:5000/api/playlists/662740198a35fcacf2c9ae71
Authorization: Bearer 
